name: CI
on:
  push:
    branches: [ main ]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Buildozer
        run: sudo apt-get update && sudo apt-get install -y build-essential ccache git zlib1g-dev python3 python3-pip python3-dev ffmpeg libsdl2-dev libffi-dev libssl-dev
      - name: Install Buildozer requirements
        run: pip3 install --user --upgrade buildozer cython==0.29.19 virtualenv
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Buildozer dependencies
        run: buildozer android debug || true
      - name: Build with Buildozer part 1
        run: buildozer android debug -v --no-pretty-print || true
      - name: Upload artifacts part 1
        uses: actions/upload-artifact@v2
        with:
          name: package1
          path: ${{ steps.buildozer.outputs.filename }}
        continue-on-error: true

  build3:
    runs-on: ubuntu-latest
    needs: [build2]
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer part 2
        run: buildozer android debug -v --no-pretty-print || true
      - name: Upload artifacts part 2
        uses: actions/upload-artifact@v2
        with:
          name: package2
          path: ${{ steps.buildozer.outputs.filename }}
        continue-on-error: true

  build4:
    runs-on: ubuntu-latest
    needs: [build3]
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer part 3
        run: buildozer android debug -v --no-pretty-print || true
      - name: Upload artifacts part 3
        uses: actions/upload-artifact@v2
        with:
          name: package3
          path: ${{ steps.buildozer.outputs.filename }}
        continue-on-error: true

  build5:
    runs-on: ubuntu-latest
    needs: [build4]
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer part 4
        run: buildozer android debug -v --no-pretty-print || true
      - name: Upload artifacts part 4
        uses: actions/upload-artifact@v2
        with:
          name: package4
          path: ${{ steps.buildozer.outputs.filename }}
        continue-on-error: true

  build6:
    runs-on: ubuntu-latest
    needs: [build5]
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer part 5
        run: buildozer android debug -v --no-pretty-print || true
      - name: Upload artifacts part 5
        uses: actions/upload-artifact@v2
        with:
          name: package5
          path: ${{ steps.buildozer.outputs.filename }}
        continue-on-error: true

