name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - name: Build with Buildozer (Job 1)
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master
        id: build1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload artifacts (Job 2)
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ needs.build.outputs.filename }}
